# Generated by Django 3.1 on 2020-08-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_frog_app', '0002_auto_20200810_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('other', 'other'), ('activity', 'activity'), ('lodging', 'lodging'), ('dining', 'dining')], default='other', max_length=20),
        ),
    ]
