# Generated by Django 3.1 on 2020-08-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_frog_app', '0005_auto_20200813_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='destination',
            field=models.CharField(default='Seattle', max_length=140),
            preserve_default=False,
        ),
    ]
